### ISSUE TITLE
[2pt] Unable to make shipment SHIPMENT-01437-2 (state and phone number)

### ISSUE THREAD

**Issue by dottenbr** [elexess/erp-shipment#120]
Unable to make shipment https://erp.eso-electronic.com/desk#Form/Shipment/SHIPMENT-01437-2

![image](https://user-images.githubusercontent.com/9136094/130196895-b5124317-195c-4afd-ad89-3bff750fcae4.png)

**Comment by francitj** [comment]
STAGING TEST FAILED.

@kkulloters error received when fetching rates. 

![image](https://user-images.githubusercontent.com/74176335/130753687-ef6b5500-6c15-4b0a-aeb5-817a23e5a1ea.png)

**Comment by kkulloters** [comment]
hello @francitj I have checked the test you made seems like your address is in China I don't think China has state 
![image](https://user-images.githubusercontent.com/40702858/130754366-8f45bcca-d7ad-4c19-be80-7b4d8e1b9c42.png)

 but if you test this in US country it works well I'm not sure if letmeship ships on a country that don't have state cos on their API they require it
![shipment](https://user-images.githubusercontent.com/40702858/130755438-3b3004d0-14a6-4ab2-a768-7f0ed8858e3f.gif)
 
@jeremythegreat01 does letmeship only ships in country with state? cos I also tried testing w/o state it gives error

**Comment by francitj** [comment]
Re-run the test with a US address, getting the below error

![image](https://user-images.githubusercontent.com/74176335/130757591-10716606-eb54-41fd-858f-b003b40a43ee.png)

**Comment by jeremythegreat01** [comment]
Hi @kkulloters, unfortunately, I am not familiar with LetMeShip.

I think we would need to:
Option A: Confirm this with LetMeShip or Dominik
Option B: Make State mandatory
Option C: Other technical suggestions to "skip" State check if the country does not have a "state" like China

Hi @francitj, do you think we can confirm this scenario with other users of Shipment DocType since Dominik is busy?

**Comment by jeremythegreat01** [comment]
Update: I think we should not go for Option B because there are cases in Production, where both recipient and sender are from Germany but only one has a State:
- Sender = https://erp.eso-electronic.com/desk#Form/Address/ESO%20Electronic%20Service%20Ottenbreit%20GmbH-Billing
- Recipient = https://erp.eso-electronic.com/desk#Form/Address/Richter%20Lighting%20Technologies%20GmbH-Shipping

(Showing links instead of screenshots because these are addresses)

**Comment by francitj** [comment]
@kkulloters Thanks vanessa. Tested it with a US address and it now works.

@jeremythegreat01 let me know if I need to create a separate issue for the creation of a proper error message.

![image](https://user-images.githubusercontent.com/74176335/130761753-95a9fac8-5d73-4961-91a9-a61020709fcf.png)

**Comment by jeremythegreat01** [comment]
Hi @francitj, I think we should be good here. I think the actual users are aware that their Recipient address has a State and create it properly on their end.

**Comment by kkulloters** [comment]
ahmm I just need to remove a code that I added for the validation so it will work on other countries let's keep this test failed for now

**Comment by jeremythegreat01** [comment]
Related Issue and Released to the User in https://github.com/elexess/erp-shipment/issues/123#issuecomment-908876277
